version: '2'

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    environment:
      - TZ=Asia/Hong_Kong
    volumes:
      - 'nexus-data:/nexus-data'
    ports:
      - '8081:8081'

volumes:
  nexus-data: {}